### ISSUE TITLE
Using images in htm file

### ISSUE THREAD

**Issue by SonnyX** [sciter-sdk/rust-sciter#53]
I can't seem to get this to work, is it unimplemented or could you provide an example?
I've tried:
```html
<picture src="icon.png"  />
<div id="main"></div>
```
with css:
```css
#main {
  height: 100%;
  width: 100%;
  background-image: url(background.png);
}
```
Both ways to load images do not seem to work.
